import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from "@vercel/speed-insights/next"

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        {children}
        <Analytics/>
        <SpeedInsights/>
      </body>
    </html>
  );
}
